version: "3.9"

services:
  pokemon:
    build: .
    image: pokemon:${TAG}
    container_name: pokemon
    network_mode: host
    pull_policy: never
  restarter:
    image: docker:cli
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do sleep 43200; docker restart pokemon; done"]
    restart: unless-stopped
    network_mode: host

networks:
  default: 
    external: true
    name: host
    
